### PR TITLE
LPS-76141 Always changing the title, not only when the showback icon is displayed

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
PR submitted to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/559 , thanks! 

@4lejandrito

**Comment by pedroqueiroz94** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
Closing in favour of https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/559.

**Pull request closed without merging**
