### PR TITLE
LPS-74668

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @leoadb, a client has recently reported a problem when displaying structure's fields tips: https://issues.liferay.com/browse/LPS-74668

Can you please confirm if the change I made is ok (not escaping the tips) and if it still keeps the prevention of XSS vulnerabilities?

Thank you!

**Comment by leoadb** [comment]
@crodriguezy Can you please send the PR to the **liferay** user? That way other team members can also review your changes. Thanks!!!

**Comment by crodriguezy** [comment]
@leoadb done! Sorry for the mistake. Link to the new PR:

https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/405

**Comment by crodriguezy** [comment]
hey @leoadb do you know if someone has had the chance to review the pull request? (liferay#405)
Tests keep on failing but I'm not sure its my (simple) change the reason.

Thank you!

**Pull request closed without merging**
